name: Test Pixi Cookiecutter

on:
  pull_request: {}
  push:
    branches: master

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.12']
        os: [ubuntu-latest]

    name: Python ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.25.0
          cache: true
          environments: dev

      - run: pixi global install direnv

      - run: pixi run fmt
      - run: pixi run lint
      - run: pixi run types
      - run: pixi run test --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


      - name: Configure git
        run: |
          git config --global user.email "default@example.com"
          git config --global user.name "Default Name"
          git config --global init.defaultBranch master

      - name: Run cookiecutter
        run: |
          pixi run cookiecutter . --no-input --config-file template_config.yml -o ..

      - name: Run pre-commit
        run: |
          cd ../pixi_project
          direnv allow .
          pixi run -e dev pre-commit run --all-files
